require '~/GitHub_Projects/HelloRuby/ruby_tool/podfile_tool.rb'
require '~/GitHub_Projects/HelloRuby/ruby_tool/dump_tool.rb'

use_frameworks!

platform :ios, '9.0'

dump_method(:install!)

target 'PodfileScript_Example' do
  pod 'PodfileScript', :path => '../'
  # pod 'SDWebImage'
  # pod 'Objective-LevelDB', '0.0.0.1'

  target 'PodfileScript_Tests' do
    inherit! :search_paths
  end
end

target 'ShareExtension' do
  pod 'PodfileScript', :path => '../'
end

post_install do |installer|
  PodfileTool.modify_xcconfig_attrs!(__FILE__, {
    'HEADER_SEARCH_PATHS' => {
      :path_to_add => [
        "${PODS_ROOT}/Headers/Public/DTIMAPI-DG/DTIMAPI",
        "${PODS_ROOT}/Headers/Public/DTIMBasicModule-DG/DTIMBasicModule"
      ],
      :path_to_remove => [
        "${PODS_CONFIGURATION_BUILD_DIR}/PodfileScript/PodfileScript.framework/Headers"
      ]
    },
    'FRAMEWORK_SEARCH_PATHS' => {
      :path_to_add => [
        "${PODS_ROOT}/Framework1",
        "${PODS_ROOT}/Framework2"
      ],
      :path_to_remove => [
        "${PODS_ROOT}/Framework3"
      ]
    },
    'OTHER_LDFLAGS' => {
      :library_to_add => [
        "MyLibrary1",
        "MyLibrary2",
      ],
      :framework_to_add => [
        "MyFramework1",
        "MyFramework2",
      ],
      :framework_to_remove => [
        "PodfileScript"
      ]
    },
    'OTHER_CFLAGS' => {
      :flag_to_add => [
        '-fmodule-map-file="${PODS_ROOT}/Headers/Public/Framework1/Framework1.modulemap"'
      ],
      :flag_to_remove => [
        '-fmodule-map-file="${PODS_ROOT}/Headers/Public/Framework2/AMPoFramework2.modulemap"'
      ]
    }
  }, ["PodfileScript_Example"], false)

  PodfileTool.resource_copy(__FILE__, nil, './copy_map.json', false)

  PodfileTool.modify_pods_project_build_settings_from_installer!(installer, {
    'APPLICATION_EXTENSION_API_ONLY' => 'NO',
  }, ['PodfileScript'], false)
  
end
