platform :ios, '10.0'

target 'HelloCocoaPods-IntegrateDynamicFramework' do
  use_frameworks!
  
  # For binrary integration, use dynamic framework
  pod 'AwesomeSDK', :path => "./AwesomeSDK/AwesomeSDK_dynamic_framework.podspec"
  
  # For source integration, use source code
  #pod 'AwesomeSDK', :path => "./AwesomeSDK/AwesomeSDK_development.podspec"
end
