platform :ios, '10.0'

target 'HelloCocoaPods-IntegrateDynamicFramework' do
  use_frameworks!
  
  # For production mode
  # pod 'AwesomeSDK', :path => "./AwesomeSDK/AwesomeSDK_production.podspec"
  
  # For development mode
  pod 'AwesomeSDK', :path => "./AwesomeSDK/AwesomeSDK_development.podspec"
end
