plugin 'cocoapods-githooks'

platform :ios, '11.0'

target 'HelloCocoaPods-Plugin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloCocoaPods-Plugin

end
